services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data                            #Pasta onde os arquivos de configuração serão disponíveis no ambiente de host ~/docker/portainer/portainer-data/
    ports:
      - 9443:9443
      - 8000:8000

volumes:
  portainer_data:
